version: '3'
services:
  database:
    image: 'mongo'
    container_name: 'mynodeapp-mongo'
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'